### ISSUE TITLE
Version 1.3.0 has a breaking change 

### ISSUE THREAD

**Issue by wy193777** [oauth-xx/oauth2#285]
My code works fine in version 1.2.0, but in 1.3.0, the server I want to connect return the following error.
```
/home/shenghan/.rvm/gems/ruby-2.4.0/gems/oauth2-1.3.0/lib/oauth2/client.rb:119:in `request': unauthorized: Full authentication is required to access this resource (OAuth2::Error)
{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}
	from /home/shenghang/.rvm/gems/ruby-2.4.0/gems/oauth2-1.3.0/lib/oauth2/client.rb:146:in `get_token'
	from /home/shenghang/.rvm/gems/ruby-2.4.0/gems/oauth2-1.3.0/lib/oauth2/strategy/client_credentials.rb:20:in `get_token'
```
Here is the options we are using to connect.

```ruby
options = {
      :site               => 'https://nvidia.jamacloud.com',
      :context_path       => '',
      :token_url          => '/rest/oauth/token',
      :rest_base_path     => '/rest/latest',
      :ssl_verify_mode    => OpenSSL::SSL::VERIFY_PEER,
      :use_ssl            => true,
      :auth_type          => :oauth,
      :client_id          => clientId,
      :client_secret      => clientSecret,
      :http_debug         => debug
 }
```

**Comment by 256dpi** [comment]
I just experienced a similar issue in my application. The code that obtained an access token using the client credentials grant suddenly didn't work anymore.

**Comment by johnwu96822** [comment]
They added an "auth_scheme" option to client, set it to :request_body, and stated: 'defaulting to :request_body to maintain backwards compatibility.' But in fact, to be backwards compatible it should have been defaulted to :basic_auth
