### ISSUE TITLE
oauth2 is not honoring Faraday middleware

### ISSUE THREAD

**Issue by djberg96** [oauth-xx/oauth2#316]
I'm using oauth2 in conjunction with Azure and I want to setup a custom middleware error handler for Faraday. However, it appears that instead of allowing Faraday errors to bubble up, the library currently raises its own `OAuth2::Error` instance. The result is that my custom handler is ignored.

Below is an example where I attempt to make a bogus request by using an invalid api-version string.

```
require 'oauth2'

# Assume I've got the client_id, client_key and tenant_id from somewhere

site_url     = 'https://login.microsoftonline.com'
token_url    = tenant_id + "/oauth2/token"
auth_url     = File.join(site_url, tenant_id, 'oauth2', 'token')
resource_url = 'https://management.azure.com/'

# Ok, no problem
client = OAuth2::Client.new(
  client_id,
  client_key,
  :site => site_url,
  :authorize_url => auth_url,
  :token_url => token_url
)

# My custom error handler for Faraday, which OAuth2 uses underneath the hood
class MyErrorHandler < Faraday::Response::Middleware
  def on_complete(env)
    case env.status
      when 400..600
        raise "OOPS: #{env.status}"
      else
        env.body
    end
  end
end

# I set the custom error handler here. Seems to accept it.
client.connection do |c|
  c.use MyErrorHandler
  c.adapter Faraday.default_adapter
end

# Yep, still working
credentials = client.client_credentials
token = credentials.get_token(:resource => resource_url)

# Deliberately use a bogus api-version string
url = 'https://management.azure.com/subscriptions?api-version=2019-09-01'

headers = {
  :accept => 'application/json',
  :content_type => 'application/json'
}

# An "InvalidApiVersionParameter" is raised. However, oauth2 raises an OAuth2::Error
# instead of using my custom error handler, which is never hooked into.
token.request(:get, url, :headers => headers)
```

**Comment by djberg96** [comment]
Note that I also tried using a block to the constructor like so:

```
Client.new(...) do |c|
  c.use MyErrorHandler
  c.adapter Faraday.default_adapter
end
```
However, when it got to `credentials.get_token` I got this error:

```
/Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http/generic_request.rb:183:in 'send_request_with_body': undefined method 'bytesize' for #<Hash:0x007fbf8c9be580> (NoMethodError)
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http/generic_request.rb:121:in 'exec'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1444:in 'block in transport_request'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in 'catch'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1443:in 'transport_request'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1416:in 'request'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1409:in 'block in request'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:877:in `start'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:1407:in `request'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:80:in 'perform_request'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in 'with_net_http_connection'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in 'call'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/response.rb:8:in 'call'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in 'build_response'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in 'run_request'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oauth2-1.4.0/lib/oauth2/client.rb:99:in 'request'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oauth2-1.4.0/lib/oauth2/client.rb:146:in 'get_token'
	from /Users/dberger/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/oauth2-1.4.0/lib/oauth2/strategy/client_credentials.rb:20:in 'get_token'
```

**Comment by djberg96** [comment]
Looking at line 183 of generic_request.rb, it appears that the `body` argument is a hash:

```
{"client_id"=>"abc", "client_secret"=>"xxx", :resource=>"https://management.azure.com/", "grant_type"=>"client_credentials"}
```
Without the block, it gets a string instead, which is what it's expecting:
```
client_id=abc&client_secret=xxx&grant_type=client_credentials&resource=https%3A%2F%2Fmanagement.azure.com%2F
```

**Comment by xtagon** [comment]
Can anyone test to see if this is still an issue on master with the new Faraday version?

**Comment by johaywood** [comment]
@djberg96 I was able to get a similar example working using client instantiation in the block form above.
```ruby
# custom_middleware_test.rb

require 'oauth2'

class MyErrorHandler < Faraday::Response::Middleware
  def on_complete(env)
    case env.status
    when 200 # requestb.in will always return a 200 OK
      raise "OOPS: #{env.status}"
    else
      env.body
    end
  end
end

builder = ->(b) {
                  b.request :url_encoded
                  b.use MyErrorHandler
                  b.adapter Faraday.default_adapter
                }

client = OAuth2::Client.new('foo', 'bar', &builder)

headers = {
            accept: 'application/json',
            content_type: 'application/x-www-form-urlencoded'
          }

client.request(:post, 'https://requestb.in/10yy5vg1', body: { foo: 'bar' },
                                                      headers: headers)
```
```bash
$ ruby custom_middleware_test.rb
test.rb:7:in `on_complete': OOPS: 200 (RuntimeError)
	from /Users/joshhaywood/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/response.rb:9:in `block in call'
	from /Users/joshhaywood/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/response.rb:61:in `on_complete'
	from /Users/joshhaywood/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/response.rb:8:in `call'
	from /Users/joshhaywood/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
	from /Users/joshhaywood/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
	from /Users/joshhaywood/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/oauth2-1.4.0/lib/oauth2/client.rb:99:in `request'
	from test.rb:31:in `<main>'
```

The error you're running into on that part is because you left out the encoding middleware `c.request url_encoded` so Faraday doesn't know how to serialize the token request body. Just keep in mind that if you want to use the same instance of `OAuth2::Token` to POST data as JSON later you might run into a situation where it's being serialized as application/x-www-form-urlencoded since that's set as the default encoding format for the Faraday connection now.

As a side note, I dug into Faraday a little more, it seems the way to modify middleware after instantiating the connection but before making a request like you were doing initially looks like this
```
client = OAuth2::Client.new('foo', 'bar')

# Insert middleware at the top of the stack
client.connection.builder.insert(0, MyErrorHandler)
```
Subbing that into the code above also works as intended.
https://github.com/lostisland/faraday/blob/master/lib/faraday/rack_builder.rb#L106

**Comment by djberg96** [comment]
@johaywood Thanks for this. I'll go ahead and close it then as it seems it was ultimately my error.
