### ISSUE TITLE
LoadError: cannot load such file -- oauth2

### ISSUE THREAD

**Issue by belgoros** [oauth-xx/oauth2#340]
I tried to load `oauth2` in the irb as follows but it failed:
```
2.4.0 :002 > require 'omniauth/oauth2'
LoadError: cannot load such file -- omniauth/oauth2
	from (irb):2:in `require'
	from (irb):2
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<top (required)>'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `load'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `kernel_load'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:28:in `run'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:424:in `exec'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:27:in `dispatch'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:18:in `start'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/bin/bundle:23:in `load'
	from /Users/Serguei/.rvm/gems/ruby-2.4.0/bin/bundle:23:in `<main>'
```
What is wring with that ? Thank you.

**Comment by galois17** [comment]
This is expected. Did you mean to do `require 'oauth2'` instead? Maybe you're referring to the omniauth gem?

**Comment by belgoros** [comment]
I had to uninstall all the previously installed omniauth* gems (`omniauth`, `omniauth-twitter`, `omniauth-oauth`), `oauth` and `oauth2` as well.
After installing just `oauth2` it worked as needed.
