### ISSUE TITLE
why I get SnakyHash OAuth2::Error?

### ISSUE THREAD

**Issue by laptopmutia** [oauth-xx/oauth2#627]
```
 token = client.auth_code.get_token(
                                     code,
                                     {
                                       redirect_uri: redirect_uri,
                                       client_id: client_id,
                                       client_secret: client_secret,
                                       grant_type: authorization_code,
                                     }
 )

/home/mutia/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/oauth2-2.0.6/lib/oauth2/access_token.rb:65:in `initialize': 
#<OAuth2::SnakyHash data=#<OAuth2::SnakyHash access_token="my_access_token" expires_in=21600 
refresh_token="my_refresh_token" scopes="basic email" token_type="Bearer"> meta=#<OAuth2::SnakyHash 
client_ip="xxx.xxx.xxx.xxx" hostname="ocan-api-xxxxxxxxxx-xxxxx" version="1">> (OAuth2::Error)
```

it also return the same with
```
 token = client.auth_code.get_token(
                                     code,
                                     {
                                       redirect_uri: redirect_uri,
                                       client_id: client_id,
                                       client_secret: client_secret,
                                       grant_type: authorization_code,
                                       parse: :json
                                     }
 )
 ```
 
 here are my latest attempt
 ```
 token = client.auth_code.get_token(
                                     code,
                                     {
                                       redirect_uri: redirect_uri,
                                       client_id: client_id,
                                       client_secret: client_secret,
                                       grant_type: authorization_code,
                                       parse: :json
                                     },
                                     {
                                       headers: {
                                         "Content-Type": "application/json"
                                       }
                                     }
)

/home/mutia/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/oauth2-2.0.6/lib/oauth2/access_token.rb:65:in `initialize': 
#<OAuth2::SnakyHash data=#<OAuth2::SnakyHash access_token="access_token" expires_in=21600 
refresh_token="refresh_token" scopes="basic email" token_type="Bearer"> headers=#<OAuth2::SnakyHash 
content_type="application/json"> meta=#<OAuth2::SnakyHash client_ip="xxx.xxx.xxx.xxx" hostname="ocan-api-xxxxxxxxx-
xxxxx" version="1">> (OAuth2::Error)
```

is it because my json response is not snake?(seems not I have use snaky false) or because it is inside `"data": { }`

because the response is this 
```
{
	"data": {
		"token_type": "Bearer",
		"expires_in": 21600,
		"scopes": "basic email",
		"access_token": "my_access_token",
		"refresh_token": "my_refresh_token"
	},
	"meta": {
		"version": "1",
		"hostname": "ocan-api-xxxxxxxxx-xxxxx",
		"client_ip": "xxx.xxx.xxx.xxx"
	}
}
```

**Comment by laptopmutia** [comment]
https://github.com/oauth-xx/oauth2/pull/511
https://github.com/oauth-xx/oauth2/pull/518

I think its related

**Comment by laptopmutia** [comment]
I think I solve this by using this 
https://github.com/oauth-xx/oauth2/pull/517

I make superclass and do hash.dig like pinterest example

**Comment by pboling** [comment]
Yes, I think it is because it is nested in `data`.  Glad you found a solution!
